version: "3.7"

services:

  first_server:
    build:
      context: ./app
    networks:
      local_network:
        ipv4_address: 172.20.0.2

  second_server:
    build:
      context: ./app
    networks:
      local_network:
        ipv4_address: 172.20.0.3

  ansible:
    build:
      context: ./ansible
    command: ansible-playbook playbook.yml
    networks:
      local_network:
        ipv4_address: 172.20.0.4

networks:
  local_network:
    driver: bridge
    name: local_network
    ipam:
      config:
        - subnet: 172.20.0.0/16